### PR TITLE
Build description

### LINKED ISSUE #2: How to build the project locally?
I would like to thank you for this example which really looks intersting and exiting. But I struggle a bit how to build it locally.

Could you please just add some instructions into the readme file, what I need to do in order to build and run it locally?

Thanks 😃

### PR DESCRIPTION
**Pull request by maraf**
Closes #2

### CODE REVIEW

**Comment by DomenPigeon** [comment]
Thanks for the response :) 
After doing everything you mention in the new docs and then running `npm run start` in the `app` folder, I still get this error:
image

**Comment by maraf** [comment]
Are you running a static web server from the `npm run build` output or do you run `npm start`?

**Comment by DomenPigeon** [comment]
Sorry for late reply. 
I am doing it like this, after I have run the command  `npm run build`
image
image

Build output:
image

**Comment by alanmoynagh** [comment]
@DomenPigeon any luck getting the issue fixed? I am also facing the same issue

**Comment by DomenPigeon** [comment]
Not really :/, but I didn't investigate any further. 
What I wanted to do is just get the .net 7 interop working locally on the client website and that worked, essentially removing the react part and replacing it with something else :)

**Comment by maraf** [comment]
I can't figure it out. I don't think it relates to .NET itself, but something with react in both library and app. 

Producing production optimized build works, but `npm start` fails the same for me.

I will investigate further.

**Pull request merged**
